= Camel SOAP to REST bridge example

This example demonstrates how to use Camel's REST DSL to expose a backend SOAP API, and the runtime is EAP.

Mainly purpose of this example
------------------------------

1. A simple camel route can brige REST invocation to legacy SOAP service.
2. Security is involved for both REST endpoint and SOAP enpoint, both backed by RH SSO. Frontend REST API protected via OAuth and OpenID Connect, and the client will fetch JWT(Json Web Token) access token from RH SSO using https://tools.ietf.org/html/rfc6749#section-4.3["Resource Owner Password Credentials"] OAuth2 mode and using this token to access the REST endpoint. In the bridge camel route, client identity is propaged from SecurityContext and when camel-cxf producer talk to the backend WS-SECURITY protected SOAP service, it will firstly using this client identity to fetch a SAML2 token issued by CXF STS service(which is backed by RH SSO as Identity Provider), and the SAML2 token is signed and put in WS-SECURITY header, and the backend WS-SECURITY protected SOAP service will validate this SAML2 token accordingly. The SOAP invocation also includes XSD Schema Validation. If the token validation is successful, the backend SOAP service will return response and the response will return to the REST client which initially sends out the request.


Prerequisites
-------------

* Maven
* An application server with Red Hat Fuse and RH SSO EAP adapter installed
    - The way to install RH SSO EAP adapter is in JBOSS_HOME folder
    1. unzip rh-sso-7.4.0-eap7-adapter.zip
    2. ./bin/jboss-cli.sh --file=bin/adapter-elytron-install-offline.cli
* RH SSO server installed

Running the example
-------------------

To run the example.

1. Start the application server in standalone mode:

    For Linux:

        ${JBOSS_HOME}/bin/standalone.sh -c standalone-full.xml

    For Windows:

        %JBOSS_HOME%\bin\standalone.bat -c standalone-full.xml
        
2. Start RH SSO in standalone mode
  
    For Linux:

        ${JBOSS_HOME}/bin/standalone.sh -Djboss.socket.binding.port-offset=100

    For Windows:

        %JBOSS_HOME%\bin\standalone.bat -Djboss.socket.binding.port-offset=100
        
3. Build and deploy the project `mvn install -Pdeploy`

Configure RH SSO
----------------
. Login RH SSO Admin Console from 
http://localhost:8180/auth with admin/admin as username/password
. In the upleft of the page click "Add Realm" button
. In the "Add Realm" page select Import "Select file" button
. Select ./src/main/resources/keycloak-config/realm-export-new.json in this example folder which will import pre-defined necessary realm/client/user/role for this example


Test
----
. Run the test
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean  test -Dtest=IntegrationTest
----

. Insight of the test
1. This test will start a backend SOAP service, which is protected by WS-Security Timestamp and Signed SAML2 token.
2. This test contains 4 test cases, demonstrates 4 different scenarios
   
   - testRestClientWithSTS: this testcase is the most normal one which tests the whole flow of the quickstart. It contains several steps
       * Test client fetch an access token from the RH SSO. Here we use the https://tools.ietf.org/html/rfc6749#section-4.3["Resource Owner Password Credentials"] OAuth2 flow, which is no UI interaction involved and suitable for Java code based client/server request/response invocation.
       * Test client puts the access token as AUTHORIZATION header and sends a REST request to the Camel REST DSL route. And the Camel REST DSL endpoint is secured by RH SSO.
       * When REST request reach Camel REST DSL route, a GetBodyProcessor is used to extract use id from the SecurityContext of the HttpServletRequest.
       * In the route, the JSON payload will be transformed to SOAP payload, then the camel-cxf producer endpoint sends SOAP request to backend SOAP service.
       * Before the camel-cxf producer endpoint sends request to backend SOAP service, it firstly talk to CXF STS(Security Token Service) to fetch a Signed SAML2 token(StsSamlCallbackHandler).
       * CXF STS checks the user id from the camel-cxf producer which is saved previously in GetBodyProcessor and calls the backend RH SSO to verify the user id(KeycloakUTValidator) as well as fetchs the roles associated with this user(KeycloakRolesClaimsHandler) and generates a signed SAML2 token and returns to camel-cxf producer.
       * camel-cxf producer puts this signed SAML2 token into SOAP message WS-SECURITY header and sends to backend SOAP service.
       * backend SOAP service unsigns this SAML2 token and validates token(Saml2Validator)
       
   - testJavaClient: this testcase won't go through camel route, instead, it's a simple JAXWS API client which sends request to backend SOAP service, but without required WS-SECURITY headers, hence an exception is expected.
   - testRestClientWithIncorrectToken : this testcase intentionally sends a request with an incorrect JWT to Camel REST DSL endpoint and expects a "HTTP 401 Unauthorized" exception; this can prove Camel REST DSL endpoint is really secured by RH SSO
   - testRestClientWithSTSInvalidZipCode : We enable schema validation for the SOAP message, and this testcase intentionally sends a request which has invalid zipcode per the XSD and expects a "cvc-pattern-valid" error
  




